### ISSUE TITLE
Dimmer vertical align missing

### ISSUE THREAD

**Issue by mic159** [semantic-ui-forest/forest-themes-css#3]
In semantic.yeti.min.css appears to be missing a style.

Its there on your example site: http://semantic-ui-forest.com/themes/bootswatch/yeti/#dimmer
But in this github repo, its missing: https://github.com/semantic-ui-forest/forest-themes-css/blob/2a7e5d0214d1188947aadb17f0eb874ea62884b4/dist/bootswatch/semantic.yeti.min.css#L260

Check semantic.yeti.min.css line 260, this style is missing:

```css
.ui.dimmer>.content>*{display:table-cell;vertical-align:middle;color:#fff}
```
